services:
  postgres:
    image: postgres:17
    container_name: oauth2_postgres
    environment:
      POSTGRES_DB: oauth2_db
      POSTGRES_USER: oauth2_user
      POSTGRES_PASSWORD: oauth2_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oauth2_user -d oauth2_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
